### ISSUE TITLE
Request to Work on Landing Page

### ISSUE THREAD

**Issue by kirankumarkm08** [kscalelabs/store#157]
I hope you're doing well. I am interested in contributing to this project and would like to work on designing and implementing a landing page.

Here are a few points I'd like to cover:

Purpose and goals of the landing page.
Key features and sections to include.
Any specific design guidelines or assets (e.g., logo, color scheme, typography).
Preferred tools or frameworks (if any).
Any other requirements or expectations.
I am excited about the opportunity to contribute and would appreciate your guidance and feedback. Please let me know if this is something I can take on and if you have any additional information to share.

Looking forward to your response!

**Comment by codekansas** [comment]
Hi @kirankumarkm08, feel free to open a PR! Would love to see what you can make!

**Comment by kirankumarkm08** [comment]
I am working on it

**Comment by codekansas** [comment]
Now that we've migrated over to using Tailwind CSS, it would be great to revisit this.

**Comment by codekansas** [comment]
similar to #183

**Comment by kirankumarkm08** [comment]
its almost done @codekansas   how to connect with you for suggestion ?

**Comment by codekansas** [comment]
discord! https://discord.gg/rhCy6UdBRD

**Comment by 2003Aditya** [comment]
hey @codekansas i also want to connect
