### ISSUE TITLE
Improve image uploading

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#164]
Some requests (can consider breaking up into multiple issues):

- [x] Fix actually uploading to the S3 bucket
- [x] Fix MIME type for images uploaded to S3
- [ ] Avoid abandoned images (i.e., images uploaded before the robot is ready)
- [x] Allow uploading JPEG files as well, not just PNGs
- [x] Show a frontend UI to crop the image before uploading it
- [x] Increase image upload size to something like 25 MB and crop later on
- [x] Drag-and-drop to upload images

Also, it seems that uploading the image doesn't work in prod. Maybe there is an issue with the S3 configuration? Here is what I see:

<img width="536" alt="image" src="https://github.com/user-attachments/assets/de237ca6-e405-434f-ab52-bec2bca8f24c">

**Comment by chennisden** [comment]
> Avoid abandoned images (i.e., images uploaded before the robot is ready)

Is the idea to upload the images to server (i.e. call the appropriate API route) upon submission of whole robot rather than upload of the image? I think this is probably the correct answer, fwiw.

Also it may be beneficial to also support uploading links for images. Now, this does open the website up to external images disappearing on us, but I'm not sure this is that big a deal.

**Comment by codekansas** [comment]
Oh we should add some drag-and-drop image thing, that would be cool

**Comment by antonyr** [comment]
@codekansas let me add drag n drop for image upload

**Comment by antonyr** [comment]
@codekansas can you please explain the meaning of abandoned images?
should we upload the image when the form is submitted?

**Comment by codekansas** [comment]
> can you please explain the meaning of abandoned images?

basically the user uploads an image, but it is not linked to a robot, so the image sits around in s3

**Comment by chennisden** [comment]
> > can you please explain the meaning of abandoned images?
> 
> basically the user uploads an image, but it is not linked to a robot, so the image sits around in s3

If you're concerned about this: what about when a user edits an image? Or deletes it from the robot? Ought we remove it from s3?

**Comment by antonyr** [comment]
@codekansas do you mean deleting images uploaded as part of creating a robot or a part? 

1. What if that image is still associated with the robot or part in the image management part of the user?
2. We can choose to delete the image in the Robot or Part page when user changes the image or cancel creating the Robot or Part?

Let me know what you think?

**Comment by codekansas** [comment]
mostly addressed with refactors
