### ISSUE TITLE
Move away from separating `Robot` and `Part`

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#184]
Instead of having separate `Robot` and `Part` schemas, we should just have something like `Listing` which encompasses any active listing. Then each listing can have associated artifacts, like URDFs, STL files, and images, which we can render for the user.

**Comment by chennisden** [comment]
Life becomes a lot easier if we remove the DOF/BOM/etc stuff in robots vs parts. Then the rendering logic can be identical and the schemas will be actually identical too.

(Realistically a lot of this stuff can be included in the description, I think?)

**Comment by chennisden** [comment]
#187
