### ISSUE TITLE
Setting project up in dev mode

### ISSUE THREAD

**Issue by swaradgat19** [kscalelabs/store#200]
Hi folks! 

I was setting up the project on my local system. I was installing the package in dev mode `(pip install -e '.[dev]')`. For some reason, it has been taking me quite a while to install it, perhaps due to the versions of the libraries not being specified in `requirements.txt`.  How much time should it ideally take?

**Comment by codekansas** [comment]
it may take some time since there's a lot of dependencies - maybe your internet connection isn't that good?
