### ISSUE TITLE
Sign and Login via Google

### ISSUE THREAD

**Issue by jayzalani** [kscalelabs/store#215]
https://github.com/user-attachments/assets/242a0047-4ce6-4a57-83c7-40ba1a9ea068
IG backend is not setup and connected properly along with proper auth.

**Comment by jayzalani** [comment]
Hi,
I encountered this issue while roaming around in website and wanted to correct it, if anyone working on this if not then please assign this to me I can fix it

**Comment by codekansas** [comment]
great :) would love to have you tackle this!
