### ISSUE TITLE
[ FEAT ] : Add Dialoag Modal to Add/Edit Robot list

### ISSUE THREAD

**Issue by senthil-athiban** [kscalelabs/store#222]
### Description

Implement a dialog modal to facilitate the addition and editing of robot list entries within the application. This feature will enhance user experience by providing a more intuitive and interactive way to manage robot lists.

**Comment by senthil-athiban** [comment]
@codekansas could you please assign me this issue?

**Comment by codekansas** [comment]
@senthil-athiban done :)
