### ISSUE TITLE
Show images to users

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#227]
- [x] For listing cards, find the first / best image associated with a listing, and show the small version of that image
- [x] For the full page, add a carousel to scroll through the various uploaded images

**Comment by kirtanchandak** [comment]
hey, can I take this task?

**Comment by codekansas** [comment]
sure!

**Comment by kirtanchandak** [comment]
Where do we need to host the images, when we are creating a listing?

**Comment by kirtanchandak** [comment]
> Where do we need to host the images, when we are creating a listing? 

I am planning to use AWS bucket and pre-signed URLs architecture for image uploading. Good approach or do you have any specific recommendations?

**Comment by codekansas** [comment]
We're hosting the images on AWS in S3 with a Cloudfront bucket in front of them - there's some config stuff that points to the correct locations in dev and prod. Specifically, images are hosted on `media.robolist.xyz`

**Comment by kirtanchandak** [comment]
> We're hosting the images on AWS in S3 with a Cloudfront bucket in front of them - there's some config stuff that points to the correct locations in dev and prod. Specifically, images are hosted on `media.robolist.xyz`

is there a endpoint to upload images in the codebase or do I need to make it?
