### ISSUE TITLE
Improve listing description editor

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#235]
- [x] Add attachments (images / URDFs / MJCFs)
- [x] Add in-line images

[Example of an improved text uploading flow](https://flowbite.com/docs/forms/textarea/#wysiwyg-editor)

**Comment by kirtanchandak** [comment]
This is related to - https://github.com/kscalelabs/store/issues/227#issue-2443725686

As the images and files getting added here should be uploaded on AWS or something which we decided to use. @codekansas what do you think?

**Comment by codekansas** [comment]
Yep, we have implemented the backend endpoint for some image uploading, however, it isn't well integrated into our current flow and we may need to refactor the backend a bit to support this behavior

**Comment by chennisden** [comment]
In-line images have been supported for a long time. After all, the editor is in Markdown.
