### ISSUE TITLE
Signin for gated pages should redirect after signin?

### ISSUE THREAD

**Issue by chennisden** [kscalelabs/store#266]
Low priority QoL

![image](https://github.com/user-attachments/assets/c41eaf7c-40d2-4415-83f1-00633fed7100)

Should take me back to /create after I sign in

**Comment by sarthakmishraa** [comment]
Hey, I am interested to work on this issue. Can you please assign it to me?

Thanks

**Comment by sarthakmishraa** [comment]
can i use useNavigate() to redirect to /create ?
