### ISSUE TITLE
More descriptive listing identifiers

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#306]
Rather than using something like `https://kscale.store/item/abf9cd3c24ccf975` as the listing identifier, we should have something like `https://kscale.store/item/ben/stompy` to identify listings

**Comment by Winston-Hsiao** [comment]
Some clarification questions/things to think about:
1. Are these something set manually by users who upload? Editable? (would be a new field on listing model called `path` or something else)
2. Have to worry about uniqueness (as it's being used for routing)
3. Have to add secondary db indexes to dynamodb for faster queries (might not be necessary)

**Comment by codekansas** [comment]
We should have some notion of usernames (and ultimately organization names), then we would have some unique identifier within that user or organization.

I think it is okay if we don't enforce uniqueness at the database level, we might not be able to express this uniqueness within the context of DynamoDB but we can add some checks for this in our CRUD.

**Comment by Winston-Hsiao** [comment]
Sounds good will think on the design/implementation plan for that.
