### ISSUE TITLE
Update Contributing Guideline After Removal of local-cors-config.json

### ISSUE THREAD

**Issue by gaurav-jo1** [kscalelabs/store#319]
In commit [#312](https://github.com/kscalelabs/store/pull/312/files), the file `local-cors-config.json` was deleted, but the Contributing Guidelines still include a command that references this file:
`aws s3api put-bucket-cors --bucket artifacts --cors-configuration file://local-cors-config.json
`

This command should be removed from the guidelines to avoid confusion.

Additionally, there are some steps in the guidelines that are currently out of order, which could lead to issues during the setup process. Specifically:

The step to initialize the test databases `python -m store.app.db create` is mentioned before setting up the virtual environment and environment variables `env.sh`. This can cause errors if the environment isn't properly set up beforehand.

If this is a valid issue, please assign it to me.

**Comment by Winston-Hsiao** [comment]
Hey nice find, feel free to go ahead and update `CONTRIBUTING.MD`!

**Comment by hthkydv** [comment]
Can i update CONTRIBUTING.MD!
