### ISSUE TITLE
Is there any need for implementing Monorepo's ?? 

### ISSUE THREAD

**Issue by jayzalani** [kscalelabs/store#320]
As the code of backend python code and frontend typescript code residing in same repo  I think it is important to do so 
here are more docs for what is monorepo/Turborepo?
https://turbo.build/repo/docs

**Comment by Winston-Hsiao** [comment]
Interesting idea looks like it could be a nice speed up for performance/dev workflow. Can you elaborate more on how you'd approach migrating/setting up our repo for Turbo?

Feel free to provide a rough implementation plan and take into consideration the current AWS build/deploy CI/CD flow.

**Comment by jayzalani** [comment]
yeah working on it will release a sample soon

**Comment by budzianowski** [comment]
Feel free to open it up again if you will see some progress.
