### ISSUE TITLE
Listings UI Improvements

### ISSUE THREAD

**Issue by Winston-Hsiao** [kscalelabs/store#324]
**1. ListingGridCards that have URDFs need a tag or some sort of indicator that a URDF is present/attached on the listing.**
ex: is "nathn zhao test :3"

<img width="1247" alt="Screenshot 2024-08-25 at 3 20 11 PM" src="https://github.com/user-attachments/assets/fdb6e427-d278-454b-bf3d-423e8f30eafb">
<img width="1221" alt="Screenshot 2024-08-25 at 3 20 42 PM" src="https://github.com/user-attachments/assets/cd065963-d4b3-433d-bc5a-5a9e5bc88217">

**2.** Add Posted at time to `ListingGridCard` and to listing page view.
**3.** Add posted by [name] to listing page view. **BLOCKED BY USER PROFILE EDIT #304**

**Comment by gaurav-jo1** [comment]
I've come up with this design, which includes:

* **URDF Indicator**: A tag to show if a URDF file is attached to the listing.
* **Creator Name Display**: The name of the creator will be shown on the card.
* **Additional Space:** The design provides more space for future add-ons.

![Stompy_new](https://github.com/user-attachments/assets/0a9ff3c3-ef6a-43aa-bd40-6084b7e40339)


If any modifications are needed, your guidance would be greatly appreciated.
I would also love to work on implementing the changes.

**Comment by Winston-Hsiao** [comment]
> I've come up with this design, which includes:
> 
> * **URDF Indicator**: A tag to show if a URDF file is attached to the listing.
> * **Creator Name Display**: The name of the creator will be shown on the card.
> * **Additional Space:** The design provides more space for future add-ons.
> 
> ![Stompy_new](https://private-user-images.githubusercontent.com/93304640/361370995-0a9ff3c3-ef6a-43aa-bd40-6084b7e40339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTk2NjIsIm5iZiI6MTcyNDY5OTM2MiwicGF0aCI6Ii85MzMwNDY0MC8zNjEzNzA5OTUtMGE5ZmYzYzMtZWY2YS00M2FhLWJkNDAtNjA4NGI3ZTQwMzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE5MDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MDVkYWU5ODYyNWQ2NmJiZTU0OGVlN2JkZmE4MzdmYzNmZGJjZWZhNTUwYTczMDM3ZmVkNjIxZGQ1ZjY0ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PmnmvKKoWnLQqWEyoLWyMTWlzvQSwV30RnGVpSWLp7E)
> 
> If any modifications are needed, your guidance would be greatly appreciated. I would also love to work on implementing the changes.

Hey, looks good! I like the overlay on the cards, and the URDF tag. 

My main concern is that for listings with URDFs that do not have an image attached there wouldn't be a background image. But otherwise it looks good. Having the overlay always positioned at the bottom rather than our current layout is a good improvement.

Feel free to implement and open up a PR and I'll review it!

**Comment by gaurav-jo1** [comment]
I've also considered the concern about listings without an image.
I have a solution in mind and will make sure to share and implement it.

**Comment by Winston-Hsiao** [comment]
Sounds good. You can mark me as a reviewer once you make the PR. 👍
