### ISSUE TITLE
View upvoted listings

### ISSUE THREAD

**Issue by Winston-Hsiao** [kscalelabs/store#338]
Give users a page to view listings they've upvoted.

New crud/routers associated with `User` and `ListingVote` models.

New page/route in `App.tsx`

On user account page have some UI element to nav to "Upvoted Listings" or "Liked Listings" page.

**Comment by ivntsng** [comment]
Hi @Winston-Hsiao ,

I'd like to work on this ticket if it's available. Let me know if you're currently working on it or if I can assist in any way. 

Looking forward to contributing!

**Comment by Winston-Hsiao** [comment]
> Hi @Winston-Hsiao ,
> 
> I'd like to work on this ticket if it's available. Let me know if you're currently working on it or if I can assist in any way.
> 
> Looking forward to contributing!

I'm not working on it currently, and I don't believe anyone else is, so feel free to take it!
