### ISSUE TITLE
User page and self management

### ISSUE THREAD

**Issue by Winston-Hsiao** [kscalelabs/store#339]
1. Listing page should show posted by [user name] and have it link to user profile.
2. Show posted listings on user profile page `/profile/[id]`

**Comment by gaurav-jo1** [comment]
Progress Update:

1. Added "By [User Name]" on the Listing Page.
2. Linked it to the User Profile.
3. Added the Profile Section to display the listings of the selected user.
4. Profile Page now shows "My Listings."


https://github.com/user-attachments/assets/95f83ea0-f6a5-4094-b216-4e420151decf

**Comment by Winston-Hsiao** [comment]
> Progress Update:
> 
> 1. Added "By [User Name]" on the Listing Page.
> 2. Linked it to the User Profile.
> 3. Added the Profile Section to display the listings of the selected user.
> 4. Profile Page now shows "My Listings."
> 
>  kscale_labs.mp4 
> Working on a few final tasks, including writing tests, reproducing and handling errors, and performing final check-ups.

Looks great, awesome work!
