### ISSUE TITLE
Not connecting with backend

### ISSUE THREAD

**Issue by Akshat76845** [kscalelabs/store#357]
Why my frontend part is not connecting with backend even after following the commands of contriubting.md.

**Comment by gaurav-jo1** [comment]
As mentioned in the `contributing.md`:

**Source the environment variables in each new terminal session.**

This means you need to run the following command:

```bash
source env.sh
```

This command is required to let the frontend know the backend URL.

Afterward, navigate to the `Frontend` directory and start the React application.
