### ISSUE TITLE
Auto-Assign First and Last Name from Google Auth

### ISSUE THREAD

**Issue by gaurav-jo1** [kscalelabs/store#372]
### Description:
Automatically assign the user's `first and/or last name` from the `Google Auth token` during sign-up. This will streamline the sign-up process by reducing the need for manual entry and improving user experience.

**Comment by Winston-Hsiao** [comment]
Feel free to handle this issue if you're interested!

**Comment by gaurav-jo1** [comment]
Sure, would love to work on it. Please assign this issue to me.
