### ISSUE TITLE
Profile Edit Shows Previously Visited User's Information

### ISSUE THREAD

**Issue by gaurav-jo1** [kscalelabs/store#410]
**Description:** When navigating from one user's profile to my own and clicking "Edit Profile," the pre-loaded information of the previously visited user's profile is displayed instead of my own information.

**Steps to Reproduce:**
Visit another user's profile.
Navigate back to your own profile.
Click on the "Edit Profile" button.
Observe that the previously visited user's information is displayed instead of your own.

**Expected Behavior:** When I navigate to my profile and click on "Edit Profile," my own profile information should be pre-loaded.

**Actual Behavior:** The information of the last visited user is loaded into the "Edit Profile" form.

**Screen Recording:**

https://github.com/user-attachments/assets/68396c9f-7311-45e2-9320-7db6a581586b

**Comment by Winston-Hsiao** [comment]
Nice find. We use the `Profile.tsx` component for both the `/account` page and `profile/{id}` pages, would be ideal to make a separate `Account.tsx` component and have that as the render for the `/account` path in `App.tsx`

**Comment by gaurav-jo1** [comment]
We can reuse the `RenderProfile` component in `Account.tsx`. The only adjustment needed is handling the API request, which was previously made in `Profile.tsx`.

Would it be alright if I worked on this issue?
