### ISSUE TITLE
Standardize the size of title cards (long names or descriptions make sizes unproportional)

### ISSUE THREAD

**Issue by is2ac2** [kscalelabs/store#87]

**Comment by is2ac2** [comment]
I meant on the robots page, where it just display a sample of each robot's information. You want to use scroll bars there? I was thinking more of a "..." type thing when the type gets too long

**Comment by chennisden** [comment]
That's also a thing you can do with the appropriate overflow class (it may actually be the better idea). Feel free to do that then

**Comment by shon3005** [comment]
tackling this issue
