### ISSUE TITLE
Make the "Success!" message after sending an email look nicer

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#89]
See image attached - looks ugly imo

<img width="383" alt="image" src="https://github.com/kscalelabs/store/assets/6070701/b2b744b5-f2d4-4765-9281-a536393eaf9e">

**Comment by chennisden** [comment]
We should also be hiding Sign In With Google

**Comment by chennisden** [comment]
> We should also be hiding Sign In With Google

Annoyingly this actually requires some rearching of the auth component. EIther we fold Email and google Auth component together (unlikely to be ideal) or we need to export some context of Success

Of course, this is unless we just decide to scrap the whole thing and make a dedicated login page. I think this is the better solution; we should figure this out after *another* userauth rearch
