### ISSUE TITLE
Add "Verified User" field (if email is verified)

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#91]
Add a "verified user" badge if the user has a valid email address, or has a linked Google / Facebook account

**Comment by chennisden** [comment]
The plan for the overall "User settings" thing is: Users wont be able to interact with any part of the website if they are not verified. So that addresses this issue in spirit

**Comment by codekansas** [comment]
We should probably have a second level of "we have verified this person to be legit and not a scammer"

**Comment by chennisden** [comment]
> We should probably have a second level of "we have verified this person to be legit and not a scammer"

Let's repurpose this issue to do that. #145 addresses email verification more fully

**Comment by Winston-Hsiao** [comment]
No longer necessary with new/current auth implementation
