### ISSUE TITLE
Add admin account type

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/store#93]
Moderator account should be able to manage other peoples' listings. Admins can make people moderators.

- [x] Add permissions on the backend marking users as admins or moderators
- [x] If a user is an admin, they should be able to make other users moderators
- [x] If a user is a moderator, they should be able to edit other peoples' listings

**Comment by chennisden** [comment]
Do you want admins to be able to make other people admins?

**Comment by codekansas** [comment]
Admin permissions should be set in a config in AWS probably

**Comment by Winston-Hsiao** [comment]
## 2 Approaches

### Approach 1 (role on user model)
1. Use permissions field on the User model, allows for 2 literals `"is_admin"` and `"is_mod`"
2. Front end interface implementation options:
a. Front end admin dashboard with interface for promoting users to moderator (has a list of all users on site or can search for them (or enter a userId to set as a moderator) and click button to call API route to update that user's permissions to moderator. 
b. Or admins when viewing another user's profile via the dynamic profile route `/profile/[userId]` have access to a `Set as Moderator` button that triggers the API route that updates that user to being a moderator.
3. API route that sets user to moderator needs to verify that currentUser triggering that action has permissions contains `"is_admin"`

### Approach 2 (admin/mod roles as part of a new `Role` model type similar to API key model)
1. ROLE
```
role_id (primary key)
role_name
```
2. USER_ROLE
```
user_id (primary key, foreign key to USERS.user_id)
role_id (primary key, foreign key to ROLES.role_id)
```
3. Similar front end, just different data model/representation and checks required to verify a user's roles/permissions.
4. Adjust API route as needed
